### ISSUE TITLE
density 

### ISSUE THREAD

**Issue by matfallet** [fiji/Directionality#5]
Dear developper, I was wondering if there is a way to extract the density of labelling from the analysis ? I have two conditions to analyse  where the directionality and the density change. Maybe it is related to the integration of  the histogram  ? You can see in this screen copy  where only the density change, in my case I have also more disorder in the second condition. (I should have changed also the orientation).

![example](https://user-images.githubusercontent.com/41480459/208466482-f3854161-9606-4a06-b1a2-ee6c9970ed65.png)

**Comment by miura** [comment]
Hi @matfallet 

With an application type of question like how to measure the density of segmented objects, I would recommend you post the same question at https://forum.image.sc/ 
GitHub issues are intended for bugs and questions specific to the implementation, so you probably would have less chance of getting responses. I will try to respond in the forum then.

Cheers, 
Kota

**Comment by matfallet** [comment]
ok thanks see the link :

https://forum.image.sc/t/plugin-directionality/75209

________________________________
De : Kota Miura ***@***.***>
Envoyé : mardi 20 décembre 2022 06:59:48
À : fiji/Directionality
Cc : Mathieu FALLET; Mention
Objet : Re: [fiji/Directionality] density (Issue #5)


Hi @matfallet<https://github.com/matfallet>

With an application type of question like how to measure the density of segmented objects, I would recommend you post the same question at https://forum.image.sc/
GitHub issues are intended for bugs and questions specific to the implementation, so you probably would have less chance of getting responses. I will try to respond in the forum then.

Cheers,
Kota

**Comment by miura** [comment]
Thanks
